runtime: nodejs16
service: opensource
instance_class: F4

env_variables:
  NODE_ENV: production
  PORT: 8080

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
