# cloudbuild.yaml
steps:
  - name: node:16.14.2
    entrypoint: npm
    args: ['install']
  - name: node:16.14.2
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
timeout: '1600s'
