

const ARRAY_KEYS = {
  LABEL: 'LABEL',
  VALUE: 'VALUE',
  COMPONENT: 'COMPONENT',
  DATA: 'DATA',
  ANGLE: 'ANGLE',
  IS_WIN: 'IS_WIN',
  FUNCTION: 'FUNCTION'
};

const BET_AMOUNTS = {
  PLATINUM: 2000,
  GOLD: 500,
  SILVER: 100
};

const wheelData2000 = [
  {
    [ARRAY_KEYS.LABEL]: '2200 Hbar',
    [ARRAY_KEYS.VALUE]: 2200,
    [ARRAY_KEYS.ANGLE]: 270,
    [ARRAY_KEYS.IS_WIN]: true
  },
  { [ARRAY_KEYS.LABEL]: '100 Hbar', [ARRAY_KEYS.VALUE]: 100, [ARRAY_KEYS.ANGLE]: 225 },
  { [ARRAY_KEYS.LABEL]: '700 Hbar', [ARRAY_KEYS.VALUE]: 700, [ARRAY_KEYS.ANGLE]: 180 },

  { [ARRAY_KEYS.LABEL]: '0 Hbar', [ARRAY_KEYS.VALUE]: 0, [ARRAY_KEYS.ANGLE]: 135 },
  {
    [ARRAY_KEYS.LABEL]: '3000 Hbar',
    [ARRAY_KEYS.VALUE]: 3000,
    [ARRAY_KEYS.ANGLE]: 90,
    [ARRAY_KEYS.IS_WIN]: true
  },
  { [ARRAY_KEYS.LABEL]: '200 Hbar', [ARRAY_KEYS.VALUE]: 200, [ARRAY_KEYS.ANGLE]: 45 },
  {
    [ARRAY_KEYS.LABEL]: '5000 Hbar',
    [ARRAY_KEYS.VALUE]: 5000,
    [ARRAY_KEYS.ANGLE]: 0,
    [ARRAY_KEYS.IS_WIN]: true
  },
  { [ARRAY_KEYS.LABEL]: '50 Hbar', [ARRAY_KEYS.VALUE]: 50, [ARRAY_KEYS.ANGLE]: 315 }
];

const wheelData500 = [
  {
    [ARRAY_KEYS.LABEL]: '700 Hbar',
    [ARRAY_KEYS.VALUE]: 700,
    [ARRAY_KEYS.ANGLE]: 270,
    [ARRAY_KEYS.IS_WIN]: true
  },
  { [ARRAY_KEYS.LABEL]: '100 Hbar', [ARRAY_KEYS.VALUE]: 100, [ARRAY_KEYS.ANGLE]: 225 },
  {
    [ARRAY_KEYS.LABEL]: '500 Hbar',
    [ARRAY_KEYS.VALUE]: 500,
    [ARRAY_KEYS.ANGLE]: 180,
    [ARRAY_KEYS.IS_WIN]: true
  },
  { [ARRAY_KEYS.LABEL]: '0 Hbar', [ARRAY_KEYS.VALUE]: 0, [ARRAY_KEYS.ANGLE]: 135 },
  { [ARRAY_KEYS.LABEL]: '300 Hbar', [ARRAY_KEYS.VALUE]: 300, [ARRAY_KEYS.ANGLE]: 90 },
  { [ARRAY_KEYS.LABEL]: '150 Hbar', [ARRAY_KEYS.VALUE]: 150, [ARRAY_KEYS.ANGLE]: 45 },
  {
    [ARRAY_KEYS.LABEL]: '1500 Hbar',
    [ARRAY_KEYS.VALUE]: 1500,
    [ARRAY_KEYS.ANGLE]: 0,
    [ARRAY_KEYS.IS_WIN]: true
  },
  { [ARRAY_KEYS.LABEL]: '50 Hbar', [ARRAY_KEYS.VALUE]: 50, [ARRAY_KEYS.ANGLE]: 315 }
];

const wheelData100 = [
  {
    [ARRAY_KEYS.LABEL]: '200 Hbar',
    [ARRAY_KEYS.VALUE]: 200,
    [ARRAY_KEYS.ANGLE]: 270,
    [ARRAY_KEYS.IS_WIN]: true
  },
  { [ARRAY_KEYS.LABEL]: '10 Hbar', [ARRAY_KEYS.VALUE]: 10, [ARRAY_KEYS.ANGLE]: 225 },
  {
    [ARRAY_KEYS.LABEL]: '100 Hbar',
    [ARRAY_KEYS.VALUE]: 100,
    [ARRAY_KEYS.ANGLE]: 180,
    [ARRAY_KEYS.IS_WIN]: true
  },
  { [ARRAY_KEYS.LABEL]: '0 Hbar', [ARRAY_KEYS.VALUE]: 0, [ARRAY_KEYS.ANGLE]: 135 },
  {
    [ARRAY_KEYS.LABEL]: '150 Hbar',
    [ARRAY_KEYS.VALUE]: 150,
    [ARRAY_KEYS.ANGLE]: 90,
    [ARRAY_KEYS.IS_WIN]: true
  },
  { [ARRAY_KEYS.LABEL]: '10 Hbar', [ARRAY_KEYS.VALUE]: 10, [ARRAY_KEYS.ANGLE]: 45 },
  {
    [ARRAY_KEYS.LABEL]: '300 Hbar',
    [ARRAY_KEYS.VALUE]: 300,
    [ARRAY_KEYS.ANGLE]: 0,
    [ARRAY_KEYS.IS_WIN]: true
  },
  { [ARRAY_KEYS.LABEL]: '10 Hbar', [ARRAY_KEYS.VALUE]: 10, [ARRAY_KEYS.ANGLE]: 315 }
];

module.exports = {
  wheelData2000,
  wheelData500,
  wheelData100,
  ARRAY_KEYS,
  BET_AMOUNTS,
};
